deb822: Better cope with sections without trailing newline
Depending on the user code, it's fairly easy to try and create Deb822SourceEntry from
a string without trailing newline, e.g.:

```python
entries = []
section = []
for line in f.readlines():
    line = rstrip()
    if not line:
        entries.append(Deb822SourceEntry('\n'.join(section), 'foo'))
        section.clear()
    else:
        section.append(line)
```

Also, some source files might not end with a new line.

A comment-only section without trailing \n would lead to an empty
`trimmed_section`, which makes TagSection choke.

I suppose a better fix would be to fix the TagSection parser but that's
in the apt code, so it's just easier to work around it here.

Note that it's not just a hypothetical issue, there is code in
`software-properties-common` that produces such paragraphs, as can be
seen with the following:

```
❯ docker run --rm ubuntu:oracular sh -c 'apt update && apt install -y software-properties-common && add-apt-repository --enable-source'
[snip]
Enabling deb-src for all repositories.

Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 632, in <module>
    sys.exit(0 if addaptrepo.main() else 1)
                  ^^^^^^^^^^^^^^^^^
  File "/usr/bin/add-apt-repository", line 599, in main
    self.global_change()
  File "/usr/bin/add-apt-repository", line 373, in global_change
    self.change_source()
  File "/usr/bin/add-apt-repository", line 346, in change_source
    self._enable_source()
  File "/usr/bin/add-apt-repository", line 313, in _enable_source
    s_entry = get_source_entry_from_list(self.sourceslist, s)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/softwareproperties/sourceutils.py", line 46, in get_source_entry_from_list
    if replace_source_entry(e, comps=set(e.comps)) == target:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/softwareproperties/sourceutils.py", line 12, in replace_source_entry
    entry = copy_source_entry(orig)
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/softwareproperties/sourceutils.py", line 6, in copy_source_entry
    return Deb822SourceEntry(str(orig), file=orig.file)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/aptsources/sourceslist.py", line 168, in __init__
    self.section = _deb822.Section(section)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/aptsources/_deb822.py", line 51, in __init__
    self.tags = collections.OrderedDict(apt_pkg.TagSection(trimmed_section))
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Unable to parse section data
```

V2: Add tests
V3: Fix typo in tests.